<a href="https://colab.research.google.com/github/jotavede/segundo-semestre-furb/blob/main/AED_%5BTurmaB_BCD%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/SEU-USUARIO/NOME-DO-REPOSITORIO/blob/main/aula01.ipynb)

**Análise Exploratória de Dados**

2026/2

In [ ]:
import pandas as pd
import numpy as np

dados = {
    "modelo": ['Onix', 'Gol', 'BYD', 'hilux', 'fusca', 'CHEVETTE'],
    "PREÇO": [75000, 40000, 142000, 231500, 25000, 7500],
    "km": [45500, 350000, 0, 78500, np.nan, 500000],
    "ANO": [2000, 1998, 2026, 2024, 1976, 1986],
    "CâmbiO": ['manual', 'manual', 'aut', 'aut', 'manual', 'manual'],
    "Combustível": ['flex', 'gasolina', 'eletrico', 'diesel', 'gasolina', 'alcool']
    }

df = pd.DataFrame(dados)
print(df)

     modelo   PREÇO        km   ANO  CâmbiO Combustível
0      Onix   75000   45500.0  2000  manual        flex
1       Gol   40000  350000.0  1998  manual    gasolina
2       BYD  142000       0.0  2026     aut    eletrico
3     hilux  231500   78500.0  2024     aut      diesel
4     fusca   25000       NaN  1976  manual    gasolina
5  CHEVETTE    7500  500000.0  1986  manual      alcool

In [ ]:
df_baratos = df[df['PREÇO'] < 100000]

print(df_baratos)

     modelo  PREÇO        km   ANO  CâmbiO Combustível
0      Onix  75000   45500.0  2000  manual        flex
1       Gol  40000  350000.0  1998  manual    gasolina
4     fusca  25000       NaN  1976  manual    gasolina
5  CHEVETTE   7500  500000.0  1986  manual      alcool

In [ ]:
filtro = df[(df['CâmbiO'] == 'manual') & (df['Combustível'] == 'alcool')]

print(filtro)

     modelo  PREÇO        km   ANO  CâmbiO Combustível
5  CHEVETTE   7500  500000.0  1986  manual      alcool

In [ ]:
df['Parcela'] = round(df['PREÇO'] / 36, 2)

print(df)

     modelo   PREÇO        km   ANO  CâmbiO Combustível  Parcela
0      Onix   75000   45500.0  2000  manual        flex  2083.33
1       Gol   40000  350000.0  1998  manual    gasolina  1111.11
2       BYD  142000       0.0  2026     aut    eletrico  3944.44
3     hilux  231500   78500.0  2024     aut      diesel  6430.56
4     fusca   25000       NaN  1976  manual    gasolina   694.44
5  CHEVETTE    7500  500000.0  1986  manual      alcool   208.33

In [ ]:
df['media_km'] = df['km'] / (2026 - df['ANO'])

print(df)

     modelo   PREÇO        km   ANO  CâmbiO Combustível  Parcela  media_km
0      Onix   75000   45500.0  2000  manual        flex  2083.33    1750.0
1       Gol   40000  350000.0  1998  manual    gasolina  1111.11   12500.0
2       BYD  142000       0.0  2026     aut    eletrico  3944.44       NaN
3     hilux  231500   78500.0  2024     aut      diesel  6430.56   39250.0
4     fusca   25000       NaN  1976  manual    gasolina   694.44       NaN
5  CHEVETTE    7500  500000.0  1986  manual      alcool   208.33   12500.0

# **SLIDE 01:organização e estruturação de dados**

## Atividade 1

In [ ]:
import pandas as pd

In [ ]:
# 1. Carragar DataFrame
dados = {
    'ID Vendedor': [101, 102, 101, 103, 104],
    'Região': ['Sul', 'NORTE', 'Sul', 'sul', 'Leste'],
    'FATURAMENTO': [5000, 3000, 5000, np.nan, 4500],
    'Email': [
        'ana@furb.br',
        'bruno@furb.br',
        'ana@furb.br',
        'carla@furb.br',
        'joao@furb.br',
    ]
}

df = pd.DataFrame(dados)
print(df)

# Carregar diretamento do Excel
#df = pd.read_excel("file_name")

   ID Vendedor Região  FATURAMENTO          Email
0          101    Sul       5000.0    ana@furb.br
1          102  NORTE       3000.0  bruno@furb.br
2          101    Sul       5000.0    ana@furb.br
3          103    sul          NaN  carla@furb.br
4          104  Leste       4500.0   joao@furb.br

In [ ]:
# 2. Renomeação das colunas

df1 = df.rename(columns={
    'ID Vendedor': 'ID_VENDEDOR',
    'Região': 'REGIAO',
    'Email': 'EMAIL'
})

print(df1)

   ID_VENDEDOR REGIAO  FATURAMENTO          EMAIL
0          101    Sul       5000.0    ana@furb.br
1          102  NORTE       3000.0  bruno@furb.br
2          101    Sul       5000.0    ana@furb.br
3          103    sul          NaN  carla@furb.br
4          104  Leste       4500.0   joao@furb.br

In [ ]:
# 3. Eliminação de duplicatas

df2 = df1.drop_duplicates(subset=['EMAIL'])
print(df2)

   ID_VENDEDOR REGIAO  FATURAMENTO          EMAIL
0          101    Sul       5000.0    ana@furb.br
1          102  NORTE       3000.0  bruno@furb.br
3          103    sul          NaN  carla@furb.br
4          104  Leste       4500.0   joao@furb.br

In [ ]:
# 4. Tratamento de Dados Ausentes

df2['FATURAMENTO'] = df2['FATURAMENTO'].fillna(0)

print(df2)

   ID_VENDEDOR REGIAO  FATURAMENTO          EMAIL
0          101    Sul       5000.0    ana@furb.br
1          102  NORTE       3000.0  bruno@furb.br
3          103    sul          0.0  carla@furb.br
4          104  Leste       4500.0   joao@furb.br

/tmp/ipykernel_598/3316359745.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['FATURAMENTO'] = df2['FATURAMENTO'].fillna(0)

In [ ]:
# 5. Criação de uma coluna calculada

df2['FATURAMENTO-ANUAL'] = df2['FATURAMENTO']*12
print(df2)

   ID_VENDEDOR REGIAO  FATURAMENTO          EMAIL  FATURAMENTO-ANUAL
0          101    Sul       5000.0    ana@furb.br            60000.0
1          102  NORTE       3000.0  bruno@furb.br            36000.0
3          103    sul          0.0  carla@furb.br                0.0
4          104  Leste       4500.0   joao@furb.br            54000.0

/tmp/ipykernel_598/1095340127.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['FATURAMENTO-ANUAL'] = df2['FATURAMENTO']*12

In [ ]:
# 5. Criação de uma nova coluna com lista de valores

df2['PERC-COMISSAO'] = [10, 20, 15, 10]
print(df2)

   ID_VENDEDOR REGIAO  FATURAMENTO          EMAIL  FATURAMENTO-ANUAL  \
0          101    Sul       5000.0    ana@furb.br            60000.0
1          102  NORTE       3000.0  bruno@furb.br            36000.0
3          103    sul          0.0  carla@furb.br                0.0
4          104  Leste       4500.0   joao@furb.br            54000.0

   PERC-COMISSAO
0             10
1             20
3             15
4             10

/tmp/ipykernel_598/2344827271.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['PERC-COMISSAO'] = [10, 20, 15, 10]

In [ ]:
# 5. Criação de uma nova coluna operando com mais de uma coluna

df2['LUCRO'] = df2['FATURAMENTO-ANUAL'] - df2['PERC-COMISSAO']/100 * df2['FATURAMENTO-ANUAL']
print(df2)

   ID_VENDEDOR REGIAO  FATURAMENTO          EMAIL  FATURAMENTO-ANUAL  \
0          101    Sul       5000.0    ana@furb.br            60000.0
1          102  NORTE       3000.0  bruno@furb.br            36000.0
3          103    sul          0.0  carla@furb.br                0.0
4          104  Leste       4500.0   joao@furb.br            54000.0

   PERC-COMISSAO    LUCRO
0             10  54000.0
1             20  28800.0
3             15      0.0
4             10  48600.0

/tmp/ipykernel_598/2443526130.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['LUCRO'] = df2['FATURAMENTO-ANUAL'] - df2['PERC-COMISSAO']/100 * df2['FATURAMENTO-ANUAL']

In [ ]:
# 6. Padronização e ordenação

df2['REGIAO'] = df2['REGIAO'].str.lower()
df2 = df2.sort_values(by='FATURAMENTO', ascending=False)

print(df2)

   ID_VENDEDOR REGIAO  FATURAMENTO          EMAIL  FATURAMENTO-ANUAL  \
0          101    sul       5000.0    ana@furb.br            60000.0
4          104  leste       4500.0   joao@furb.br            54000.0
1          102  norte       3000.0  bruno@furb.br            36000.0
3          103    sul          0.0  carla@furb.br                0.0

   PERC-COMISSAO    LUCRO
0             10  54000.0
4             10  48600.0
1             20  28800.0
3             15      0.0

In [ ]:
# 7. Exportação Final

df2.to_excel('dados_processados.xlsx', index=False)
df2.to_csv('dados_processados.csv', index=False)

## Atividade 2

In [ ]:
import pandas as pd

In [ ]:
# 1. Carregando os dados no Formato Largo (Wide)
df_notas = pd.DataFrame({
    'Estudante': ['Alice', 'Bruno', 'Carla'],
    'Matematica': [8.5, 7.0, 9.5],
    'Ciencias': [9.0, 6.5, 8.0],
    'Historia': [7.0, 8.0, 8.5]
})

print(df_notas)

In [ ]:
# 2. Transformando em Formato Longo com pd.melt()

df_longo = pd.melt(df_notas,
                   id_vars=['Estudante'],
                   value_vars=['Matematica', 'Ciencias', 'Historia'],
                   var_name='Disciplina',
                   value_name='Nota')

print(df_longo)

In [ ]:
# 3. Reorganizando com pd.pivot()

df_boletim = df_longo.pivot(index='Estudante',
                            columns='Disciplina',
                            values='Nota')

print("\nTabela Pivoteada (Retorno ao Formato Largo):")
print(df_boletim)

## Atividade 3

In [ ]:
import pandas as pd

In [ ]:
# 1. Criando as tabelas

df_alunos = pd.DataFrame({
    'id_aluno': [1, 2, 3, 4, 5],
    'Nome': ['Ana', 'Bruno', 'Carlos', 'Diana', 'Eduardo']
})

df_novos_alunos = pd.DataFrame({
    'id_aluno': [6, 7, 8, 9, 10],
    'Nome': ['Fernanda', 'Gabriel', 'Helena', 'Igor', 'Julia']
})

df_notas = pd.DataFrame({
    'id_aluno': [1, 2, 4, 6, 8, 11],
    'Nota_Final': [8.5, 7.0, 9.2, 6.5, 8.0, 10.0]
})

print('df_alunos')
print(df_alunos,'\n')
print('df_novos_alunos')
print(df_novos_alunos,'\n')
print('df_notas')
print(df_notas)

df_alunos
   id_aluno     Nome
0         1      Ana
1         2    Bruno
2         3   Carlos
3         4    Diana
4         5  Eduardo

df_novos_alunos
   id_aluno      Nome
0         6  Fernanda
1         7   Gabriel
2         8    Helena
3         9      Igor
4        10     Julia

df_notas
   id_aluno  Nota_Final
0         1         8.5
1         2         7.0
2         4         9.2
3         6         6.5
4         8         8.0
5        11        10.0

In [ ]:
# 2. Empilhar as listas de alunos

df_alunos_completo = pd.concat([df_alunos, df_novos_alunos], ignore_index=True)

print('df_alunos_completo')
print(df_alunos_completo)

df_alunos_completo
   id_aluno      Nome
0         1       Ana
1         2     Bruno
2         3    Carlos
3         4     Diana
4         5   Eduardo
5         6  Fernanda
6         7   Gabriel
7         8    Helena
8         9      Igor
9        10     Julia

In [ ]:
# 3. Cruzamento da lista de alunos com o registro das notas

df_relatorio_final = pd.merge(df_alunos_completo,
                              df_notas,
                              on='id_aluno',
                              how='outer')

print("df_relatorio_final")
print(df_relatorio_final)

df_relatorio_final
    id_aluno      Nome  Nota_Final
0          1       Ana         8.5
1          2     Bruno         7.0
2          3    Carlos         NaN
3          4     Diana         9.2
4          5   Eduardo         NaN
5          6  Fernanda         6.5
6          7   Gabriel         NaN
7          8    Helena         8.0
8          9      Igor         NaN
9         10     Julia         NaN
10        11       NaN        10.0

## Atividade 4

In [ ]:
import pandas as pd

In [ ]:
# 1. Criando as tabelas: usar o DataFrame df_relatorio_final da atividade 3

# 2. Filtrar alunos que estão sem nota (NaN)

sem_nota = df_relatorio_final.loc[df_relatorio_final['Nota_Final'].isna()]

print(sem_nota)

   id_aluno     Nome  Nota_Final
2         3   Carlos         NaN
4         5  Eduardo         NaN
6         7  Gabriel         NaN
8         9     Igor         NaN
9        10    Julia         NaN

In [ ]:
# 3. Filtrar os 3 primeiros registros (posições 0, 1 e 2)
tres_primeiros = df_relatorio_final.iloc[0:3]

print(tres_primeiros)

   id_aluno    Nome  Nota_Final
0         1     Ana         8.5
1         2   Bruno         7.0
2         3  Carlos         NaN

In [ ]:
# 4. Filtros por linha e coluna

filtro = df_relatorio_final.iloc[0:3, 2]

print(filtro)

0    8.5
1    7.0
2    NaN
Name: Nota_Final, dtype: float64

# **Aula 2** - Mensagem Chave de Conhecimento:

**Formato Largo (Ideal para Leitura +compacto) =** Formato de dados que pode crescer tanto Horizontal quanto Verticalmente. Exemplo, se em uma planilha temos 'IDs' de produtos, por exemplo, esse seria um dado vertical onde, na suas colunas (horizontal) teríamos dados sobre tais produtos, como Preço, Estoque, etc.

**Formato Longo (Ideal para leitura da Máquina) =** Formato de dados que pode crescer somente verticalmente, é onde os

'pd.melt()' =

**Atividade usando pd.melt()**

In [1]:
import pandas as pd

In [2]:
# Exemplo prático de pd.melt()

# 1. Criar um DataFrame em formato "largo"
dados_alunos = {
    'Alunos': ['1', '2'],
    'AED': [6, 10],
    'POO': [7, 9,],
    'LOG': [8, 8]
}
df_alunos_largo = pd.DataFrame(dados_alunos)

print("DataFrame Original (Formato Largo):")
display(df_alunos_largo)

# 2. Usar pd.melt() para transformar para o formato "longo"
df_alunos_longo = pd.melt(df_alunos_largo,
                          id_vars=['Alunos'],
                          value_vars=['AED', 'POO', 'LOG'],
                          var_name='Disciplina',
                          value_name='Nota')

print("\nDataFrame Transformado (Formato Longo) com pd.melt():")
display(df_alunos_longo)

DataFrame Original (Formato Largo):

  Alunos  AED  POO  LOG
0      1    6    7    8
1      2   10    9    8

DataFrame Transformado (Formato Longo) com pd.melt():

  Alunos Disciplina  Nota
0      1        AED     6
1      2        AED    10
2      1        POO     7
3      2        POO     9
4      1        LOG     8
5      2        LOG     8